version: '3.8'

services:
  fastapi:
    build: .  # Builds using Dockerfile in current directory
    ports:
      - "8001:8001"
    volumes:
      - /var/lib/jenkins/workspace/Devops_asgn_2.0/app:/app  # Mounts host directory to container
